project:
  type: website

website:
  title: "Edo"
  site-url: 'https://edoardocostantini.github.io'
  site-path: '/'
  navbar:
    left:
      - text: "Digital garden"
        menu:
          - all-posts.qmd
          - series-pca.qmd
          - series-sm-course.qmd
          - series-sampling.qmd
      - href: research.qmd
        text: Research
     
format:
  html:
    theme: 
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
    css: styles.css
    toc: true
  