project:
  type: website

website:
  title: "Edoardo Costantini"
  site-url: 'https://edoardocostantini.github.io'
  site-path: '/'
  navbar:
    left:
      - text: "Digital garden"
        menu:
          - all-posts.qmd
          - series-pca.qmd
          - series-sm-course.qmd
          - series-sampling.qmd
      - href: research.qmd
        text: Research 

format:
  html:
    theme: flatly
    toc: true
  