project:
  type: website

website:
  title: "Edoardo Costantini"
  site-url: 'https://edoardocostantini.github.io'
  site-path: '/'
  sidebar:
    style: "floating"
    search: true
    contents:
      - research.qmd
      - section: "Digital garden"
        contents:
          - all-posts.qmd
          - series-pca.qmd
          - series-sm-course.qmd
          - series-sampling.qmd
      - section: "Research"
        contents: 
          - mi-gspcr.qmd
          - mi-hd.qmd
          - mi-pcr.qmd
          - mi-spcr.qmd

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
